### ISSUE TITLE
iTechX | CS211 Advance Computer Architecture

### ISSUE THREAD

**Issue by victoryang00** [i-TechX/iTechX#40]
The url for Fall 2021 should be https://toast-lab.sist.shanghaitech.edu.cn/courses/CS211@ShanghaiTech/Fall-2021/ .

**Comment by why-in-Shanghaitech** [comment]
Ok, I'll fix this.

**Comment by why-in-Shanghaitech** [comment]
Erm... Does this page have anything different from the gitee page?

**Comment by victoryang00** [comment]
The ppt after mid term is released there.

**Comment by why-in-Shanghaitech** [comment]
Same in gitee page?

**Comment by why-in-Shanghaitech** [comment]
Since no more info, I'll close this issue for now.
