### ISSUE TITLE
Duplicated CS101 Fall 2021

### ISSUE THREAD

**Issue by itsuitsuki** [i-TechX/iTechX#96]
as the screenshot
![image](https://github.com/i-TechX/iTechX/assets/110326128/84626472-e97f-481c-ac69-434ec9f7df52)

**Comment by why-in-Shanghaitech** [comment]
Hi! Thank you for the reminder. As you can see, these are two different classes (CS101.01, CS101.02), with different instructors. In Fall 2021, these two classes shared the same teaching assistants.

**Comment by itsuitsuki** [comment]
OK, get it
